baseURL: "https://samiakabir.github.io/"
title: Samia Kabir
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
  twitter: SamiaKabir12

taxonomies:
  tag: tags

menu:
  main:
    - name: Projects
      url: /projects/
      weight: 1
    - name: Publication
      url: /papers/
      weight: 2
    - name: Teaching
      url: /courses/
      weight: 3
    - name: News
      url: /news/
      weight: 4
    # - name: Archive
    #   url: /archive/
    #   weight: 5

params:
  description: "I'm a 3rd year Ph.D. student in Computer Science at Purdue University. My research interest is in the intersection of Natural Language Processing, Information Visualization, and Human-AI Interaction. I am currently a part of the Human-Centered Software Systems Lab at Purdue,  working under the supervision of [Dr. Tianyi Zhang](https://tianyi-zhang.github.io/)."
  author: Samia Kabir
  # googleAnalyticsID: ""
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Samia Kabir
    subtitle: "Hello! This is Samia! I'm a 3rd year Ph.D. student in Computer Science at Purdue University. My research interest is
     in the intersection of Natural Language Processing, Information Visualization,
     and Human-AI Interaction. I am currently a part of the Human-Centered Software Systems Lab at Purdue,
     working under the supervision of [Dr. Tianyi Zhang](https://tianyi-zhang.github.io/).

     <br><br>
     Before coming to Purdue, I received my M.Sc. in Computer Science and Engineering from  Texas A&M University in May 2020.
     I completed my Bachelor's degree from Bangladesh University of Engineering and Technology(BUET). I grew up in the magical  Dhaka city of  Bangladesh.
     I love reading fiction ðŸ“–, and like many other grad students, I'm a huge plant lover! ðŸŒµðŸŒ±

     <br> <br>

     Thank you for visitng my webpage!
     "
    imageUrl: "/picture.jpeg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: Samia Kabir
    buttons:
      - name: Projects
        url: /projects/
      - name: Publication
        url: /papers/
      - name: Teaching
        url: /courses/
      - name: News
        url: /news/

  socialIcons:
    - name: CV
      url: "/cv.pdf"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/samia-kabir/"
    - name: Google Scholar
      url: "https://scholar.google.com/citations?user=DZ5jg-IAAAAJ&hl=en"
    - name: GitHub
      url: "https://github.com/SamiaKabir"

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: true
    hiddenInSingle: true
  label:
    text: "Samia Kabir"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: xcode
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
# max number of characters:
# * title: 70
# * description: 120â€“155
# * summary: 265
