baseURL: "https://pascalmichaillat.org/" 
title: Pascal Michaillat
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: pmichaillat

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        - name: Design
          url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 4
        - name: Archive
          url: /archive/
          weight: 5

params:
    description: "I am an Associate Professor of Economics at Brown University. I work on unemployment, economic slack, business cycles, macroeconomic policy, metascience."
    author: Pascal Michaillat
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pascal Michaillat
          subtitle: "I am an Associate Professor of Economics at Brown University. I work on unemployment, economic slack, business cycles, macroeconomic policy, and science-related topics. In January–June 2023, I am visiting the University of California–San Diego."
          imageUrl: "/picture.jpeg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Pascal Michaillat
          buttons:
            - name: Papers
              url: /papers/
            - name: Courses
              url: /courses/
            - name: Design
              url: /design/
    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Google Scholar
          url: "https://scholar.google.com/citations?user=cL23w-4AAAAJ"
        - name: Email
          url: "mailto:pascalmichaillat@gmail.com"
        - name: Location
          url: /location/
        - name: Office Hours
          url: /officehours/
        - name: GitHub
          url: "https://github.com/pmichaillat"
        - name: YouTube
          url: "https://www.youtube.com/@pmichaillat"
        - name: Substack
          url: "https://pmichaillat.substack.com"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Pascal Michaillat"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
